AWSTemplateFormatVersion: 2010-09-09
Description: |
  Simple static website using one EC2 and sg

Parameters:
  pImageId:
    Description: Latest Amazon Linux Ami ID
    Type: AWS::EC2::Image::Id
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
  
  pKeyPair:
    Description: Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName
    Default: 

Resources: 
  rSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable ssh and HTTP for web server"
      SecurityGroupIngress:
      - IpProtocol: TCP
        ToPort: 22
        FromPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: TCP
        ToPort: 80
        FromPort: 80
        CidrIp: 0.0.0.0/0
  rWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref pImageId 
      InstanceType: t2.micro
      KeyName: !Ref pKeyPair
      SecurityGroups:
      - !GetAtt rSecurityGroup.GroupId
      Tags: 
      - Key: Name
        Value: ms-web-sever
        # UserData: "String"

  
# Outputs: