- name: Copy it to node1
  hosts: node1
  vars:
    ip_address: 172.31.29.218
  tasks:
    - name: copy ip adress
      ansible.builtin.copy:
        content: "Private IP address of this node is {{ ip_address }}"
        dest: /home/ec2-user/myfile
- name: Copy ip to node2
  vars:
    ip_address: 172.31.29.000
  hosts: node2
  tasks:
    - name: copy ip address to node2
      ansible.builtin.copy:
        content: "Private IP address of this node is {{ ip_address }}"
        dest: /home/ec2-user/myfile
